# -*- coding: utf-8 -*-
"""MelgarMontano_Fase3_Proyecto

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mFOYNkSTCVtZphNvN-6ne2qKFH8l9XlH

🚨 PROPUESTA DE VISOR: Sistema de Alerta Temprana (SAT) | Cuenca Río Lempa
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# 
# # 1. CONFIGURACIÓN VISUAL:
# st.set_page_config(
#     page_title="SAT Río Lempa | Geoportal Hidroclimático",
#     page_icon="🚨",
#     layout="wide",
#     initial_sidebar_state="expanded"
# )
# 
# # Estilos CSS para tarjetas de métricas, alertas del SAT y bordes - según uso de marca SRL
# # Paleta Institucional Somos Río Lempa:
# # Primarios: #149fda (Azul), #089e49 (Verde), #f18e21 (Naranja)
# # Secundarios: #133b62 (Azul Oscuro 1), #0c4e84 (Azul Oscuro 2)
# 
# st.markdown("""
#     <style>
#         @import url('https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,600;0,700;1,400&display=swap');
# 
#         /* 1. Aplicar Sitka solo a textos generales, PROTEGIENDO los iconos del sistema */
#         html, body, h1, h2, h3, h4, h5, h6, .stMarkdown, .stText, p {
#             font-family: 'Sitka Text', 'Sitka Small', 'Sitka Display', 'Sitka Banner', 'Sitka', 'Lora', Georgia, serif !important;
#             color: #1e293b !important;
#         }
# 
#         /* 2. Fondo blanco puro */
#         .stApp {
#             background-color: #ffffff !important;
#         }
# 
#         /* 3. Barra lateral clara y limpia */
#         section[data-testid="stSidebar"] {
#             background-color: #f8fafc !important;
#             border-right: 1.5px solid #e2e8f0;
#         }
#         section[data-testid="stSidebar"] * {
#             color: #1e293b !important;
#         }
# 
#         /* 4. EVITAR QUE EL TÍTULO DE LA BARRA LATERAL SE MARQUE EN DOS LÍNEAS */
#         section[data-testid="stSidebar"] h1 {
#             font-size: 1.35rem !important;
#             white-space: nowrap;
#         }
# 
#         /* 5. Corrección de cajas desplegables (selectores) */
#         div[data-baseweb="select"] > div {
#             background-color: #f1f5f9 !important;
#             border-color: #cbd5e1 !important;
#         }
#         div[data-baseweb="select"] span, div[data-baseweb="select"] div {
#             color: #1e293b !important;
#         }
# 
#         /* 6. Tarjetas KPI */
#         div[data-testid="metric-container"] {
#             background-color: #f8fafc !important;
#             border: 1px solid #cbd5e1 !important;
#             padding: 16px;
#             border-radius: 8px;
#             border-left: 6px solid #149fda !important;
#             box-shadow: 0 2px 5px rgba(0, 0, 0, 0.04);
#         }
#         div[data-testid="metric-container"] label {
#             color: #475569 !important;
#         }
#         div[data-testid="metric-container"] div[data-testid="stMetricValue"] {
#             color: #0f172a !important;
#         }
# 
#         .banner-semaforo {
#             padding: 18px; border-radius: 8px; margin-bottom: 20px;
#             font-family: 'Sitka Text', 'Sitka', Georgia, serif;
#             box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.06);
#         }
# 
#         .block-container {
#             padding-top: 2rem; padding-bottom: 2rem; padding-left: 2.5rem; padding-right: 2.5rem;
#         }
#     </style>
# """, unsafe_allow_html=True)
# 
# # 2. BARRA LATERAL: CONTROLADOR METEOROLÓGICO Y FILTROS
# 
# with st.sidebar:
#     st.title("🎛️ Panel Operativo SAT")
#     st.markdown("---")
# 
#     st.subheader("🌧️ Simulador de Tormentas")
#     st.write("Evalúa la respuesta del territorio ante pronósticos meteorológicos de 24 horas:")
# 
#     # Deslizador meteorológico idéntico a tu widget de Colab (Paso 10 en Proyecto)
#     lluvia_evaluar = st.slider(
#         "Pronóstico de Lluvia (mm/día):",
#         min_value=0.0,
#         max_value=150.0,
#         value=45.0,
#         step=5.0,
#         help="Mueve el deslizador para simular la intensidad de la lluvia en la cuenca."
#     )
# 
#     st.markdown("---")
#     st.subheader("📍 Selección Territorial")
# 
#     # SUBCUENCA DE INTERÉS - SELECCIONADA:
#     subcuenca_id = st.selectbox(
#         "Subcuenca Nivel 12 (HydroSHEDS):",
#         ["7070016490 (Cuenca Muestra Lempa)", "7070870860 (Tamulasco / Alta)", "7070870890 (Media)", "7070870910 (Baja)"]
#     )
# 
#     modulo_sat = st.radio(
#         "Módulo de Evaluación:",
#         ["🌊 Inundaciones (Escorrentía Corto Plazo)", "☀️ Sequías (Índice SPI Mediano Plazo)"]
#     )
# 
#     st.markdown("---")
#     st.caption("Propuesta por: **Susana M. Melgar** | Programa *Somos Río Lempa*")
# 
# 
# # 3. ENCABEZADO PRINCIPAL Y TARJETAS DE INDICADORES
# 
# st.title("🚨 Sistema de Alerta Temprana (SAT) | Cuenca Río Lempa")
# st.markdown("**Clasificación Espacial de Riesgos Hidroclimáticos y Directrices Operativas para el Plan de Manejo**")
# 
# # Parámetros de referencia extraídos de tu pre-cálculo CHIRPS (Paso 8 y 10)
# P90_REF = 35.0
# P95_REF = 55.0
# P99_REF = 90.0
# 
# col_kpi1, col_kpi2, col_kpi3, col_kpi4 = st.columns(4)
# col_kpi1.metric("Unidades de Drenaje", "139 Subcuencas", "HydroSHEDS Nivel 12")
# col_kpi2.metric("Umbral Preventivo (P90)", f"{P90_REF} mm/día", "Monitoreo cauces")
# col_kpi3.metric("Umbral Crítico (P95)", f"{P95_REF} mm/día", "Restricción agrícola")
# col_kpi4.metric("Umbral Emergencia (P99)", f"{P99_REF} mm/día", "Evacuación obligatoria", delta_color="inverse")
# 
# st.markdown("---")
# 
# 
# # 4. LÓGICA DINÁMICA DEL SEMÁFORO - Para mí, lo improtante del sistema SAT y de fácil entendimiento.
# 
# if modulo_sat == "🌊 Inundaciones (Escorrentía Corto Plazo)":
#     if lluvia_evaluar >= P99_REF:
#         alerta_nivel = "🔴 ALERTA ROJA - EMERGENCIA POR ESCORRENTÍA"
#         bg_color, bord_color, txt_color = "#fef2f2", "#e74c3c", "#991b1b" # Fondo rosado pastel, texto rojo vino
#         accion_sat = "EVACUACIÓN OBLIGATORIA en zonas vulnerables detectadas en el DEM (pendientes planas < 5° propensas a acumulación rápida)."
#     elif lluvia_evaluar >= P95_REF:
#         alerta_nivel = "🟠 ALERTA NARANJA - ESTADO CRÍTICO"
#         bg_color, bord_color, txt_color = "#fff7ed", "#f18e21", "#9a3412" # Fondo melocotón, texto naranja oscuro
#         accion_sat = "RESTRICCIÓN TEMPORAL de actividades agrícolas en riberas, llanuras aluviales y zonas de desbordamiento."
#     elif lluvia_evaluar >= P90_REF:
#         alerta_nivel = "🟡 ALERTA AMARILLA - FASE PREVENTIVA"
#         bg_color, bord_color, txt_color = "#fefce8", "#f1c40f", "#854d0e" # Fondo crema, texto ámbar oscuro
#         accion_sat = "ACTIVACIÓN DE COMITÉS DE CUENCA y monitoreo intensivo de los niveles en cauces principales del Río Lempa."
#     else:
#         alerta_nivel = "🟢 ALERTA VERDE - SISTEMA ESTABLE"
#         bg_color, bord_color, txt_color = "#f0fdf4", "#089e49", "#166534" # Fondo menta suave, texto verde bosque
#         accion_sat = "Precipitación dentro de la capacidad de carga hidrológica regular. Continuar labores de monitoreo estándar."
# else:
#     alerta_nivel = "☀️ MONITOREO DE SEQUÍA ESTACIONAL (ÍNDICE SPI)"
#     bg_color, bord_color, txt_color = "#fefce8", "#f39c12", "#854d0e"
#     accion_sat = "Evaluación mensual: Para SPI < -1.0 activar protocolos de conservación de humedad. Para SPI < -1.5 restringir concesiones de agua superficial."
# 
# # Banner principal ajustado a texto oscuro (#1e293b y #475569) para perfecta lectura en fondo blanco
# st.markdown(f"""
#     <div class='banner-semaforo' style='background-color: {bg_color}; border-left: 8px solid {bord_color}; border: 1px solid {bord_color};'>
#         <div style='font-size: 14px; color: #475569;'>📍 <b>EVALUACIÓN TERRITORIAL: {subcuenca_id}</b> &nbsp;|&nbsp; Escenario simulado: <b style='color: #0f172a;'>{lluvia_evaluar} mm/día</b></div>
#         <div style='font-size: 22px; font-weight: bold; color: {txt_color}; margin: 8px 0;'>{alerta_nivel}</div>
#         <div style='font-size: 15px; color: #1e293b;'>📋 <b style='color: {txt_color};'>Directriz Institucional del Plan de Manejo:</b> {accion_sat}</div>
#     </div>
# """, unsafe_allow_html=True)
# 
# # 5. PESTAÑAS DE VISUALIZACIÓN DE TUS RESULTADOS
# 
# tab_mapa, tab_series, tab_plan, tab_datos = st.tabs([
#     "🗺️ Zonificación del Riesgo (Mapa)",
#     "📊 Serie Histórica & Umbrales",
#     "📋 Directrices Plan de Manejo",
#     "📥 Evidencias & Metadatos"
# ])
# 
# 
# # PESTAÑA 1: MAPA DE RESULTADOS
# 
# with tab_mapa:
#     st.subheader("Cartografía Hidromorfométrica del Río Lempa")
#     st.write("Superposición de las 139 subcuencas (Nivel 12 HydroSHEDS) sobre el Modelo Digital de Elevación (SRTM) y precipitación CHIRPS:")
# 
#     col_mapa1, col_mapa2 = st.columns([3, 1])
# 
#     with col_mapa1:
#         # Imagen #1 DEM + Subcuencas:
#         st.image(
#             "https://res.cloudinary.com/dm1cbskuj/image/upload/v1785208673/s4ih0oiaqqzga2oasvru.jpg",
#             caption=f"Zonificación espacial para la {subcuenca_id}.",
#             use_container_width=True
#         )
# 
#     with col_mapa2:
#         st.markdown("### 📌 Atributos de Cuenca")
#         st.info("**Resolución SRTM:** 30 metros\n\n**Resolución CHIRPS:** 5,566 metros (Diaria)\n\n**Sistema de Referencia:** WGS 84 (Nativo geográfico)")
#         st.markdown("### 🏔️ Susceptibilidad")
#         st.write("Las zonas de ladera (> 25°) presentan alto riesgo de erosión, mientras que los valles (< 5°) concentran el riesgo de inundación rápida.")
# 
# # PESTAÑA 2: GRÁFICOS ESTADÍSTICOS (SERIES Y UMBRALES)
# 
# with tab_series:
#     st.subheader("Calibración de Umbrales Matemáticos (CHIRPS 1981-2025)")
#     st.write("Comportamiento estacional y delimitación de líneas de alerta para la toma de decisiones:")
# 
#     col_graf1, col_graf2 = st.columns(2)
# 
#     with col_graf1:
#         st.markdown("#### 1️⃣ Serie de Tiempo y Percentiles (P95 / P99)")
#         # Gráfico:
#         st.image(
#             "https://res.cloudinary.com/dm1cbskuj/image/upload/v1785209004/fdcn5kelokudxxt5u5jr.jpg",
#             caption="Serie histórica de precipitación y umbrales P95/P99.",
#             use_container_width=True
#         )
# 
#     with col_graf2:
#         st.markdown("#### 2️⃣ Estacionalidad Mensual Promedio")
#         # Gráfico dinámico simulando tu estacionalidad de El Salvador (Época seca vs. lluviosa)
#         meses = ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"]
#         lluvia_promedio = [5.2, 8.1, 14.5, 55.0, 180.4, 310.2, 270.5, 295.0, 360.8, 210.3, 75.0, 15.0]
#         df_estacional = pd.DataFrame({"Mes": meses, "Precipitación (mm)": lluvia_promedio}).set_index("Mes")
# 
#         st.bar_chart(df_estacional, color="#149fda")
#         st.caption("Distribución mensual mostrando el pico máximo de escorrentía en junio y septiembre.")
# 
# 
# # PESTAÑA 3: DIRECTRICES DEL PLAN DE MANEJO
# 
# with tab_plan:
#     st.subheader("Matriz Institucional de Acción Territorial")
#     st.write("Directrices vinculadas directamente al Plan de Manejo de la Cuenca del Río Lempa:")
# 
#     st.markdown("### 🌊 Protocolo de Inundaciones por Escorrentía")
#     col_p1, col_p2, col_p3 = st.columns(3)
#     with col_p1:
#         st.warning(f"**🟡 ALERTA AMARILLA (P90: {P90_REF} mm)**\n\nActivación inmediata de los comités locales de cuenca y monitoreo de las estaciones hidrométricas en cauces principales.")
#     with col_p2:
#         st.error(f"**🟠 ALERTA NARANJA (P95: {P95_REF} mm)**\n\nRestricción de labores agrícolas en riberas. Movilización de ganado y maquinaria de las llanuras aluviales de inundación.")
#     with col_p3:
#         st.markdown(f"<div style='background-color:#900c3f; color:white; padding:15px; border-radius:5px;'><b>🔴 ALERTA ROJA (P99: {P99_REF} mm)</b><br><br>EVACUACIÓN OBLIGATORIA de asentamientos humanos en zonas con pendiente < 5° propensas a desbordamientos.</div>", unsafe_allow_html=True)
# 
#     st.markdown("---")
#     st.markdown("### ☀️ Protocolo de Sequías (Índice SPI - Gamma Distribution)")
#     st.info("**⚠️ SPI < -1.0 (Sequía Moderada):** Implementación de técnicas de conservación de humedad de suelos, rastrojos y ajustes en los calendarios de siembra de granos básicos.\n\n**🚨 SPI < -1.5 (Sequía Severa):** Restricción temporal y racionamiento de las concesiones de extracción de agua superficial en las subcuencas afectadas.")
# 
# # PESTAÑA 4: EVIDENCIAS Y DESCARGA DE METADATOS
# 
# with tab_datos:
#     st.subheader("📥 Exportación de Datos Tabulares para Reportes")
#     st.write("Genera el respaldo técnico de la subcuenca monitoreada para anexar a tus informes de *Somos Río Lempa*:")
# 
#     # Tabla simulada con las variables exactas de tu proyecto
#     df_metadatos = pd.DataFrame([{
#         "HYBAS_ID": subcuenca_id.split(" ")[0],
#         "Pais_Monitoreo": "El Salvador",
#         "Lluvia_Simulada_mm": lluvia_evaluar,
#         "Umbral_P90": P90_REF,
#         "Umbral_P95": P95_REF,
#         "Umbral_P99": P99_REF,
#         "Estado_Alerta": alerta_nivel.split(" - ")[0],
#         "Resolucion_DEM": "30m (SRTM)",
#         "Resolucion_Clima": "Daily CHIRPS"
#     }])
# 
#     st.dataframe(df_metadatos, use_container_width=True)
# 
#     csv_bytes = df_metadatos.to_csv(index=False).encode('utf-8')
#     st.download_button(
#         label="📄 Descargar Ficha Técnica Territorial (CSV)",
#         data=csv_bytes,
#         file_name=f"Reporte_SAT_Lempa_{subcuenca_id.split(' ')[0]}.csv",
#         mime="text/csv",
#         type="primary"
#     )

import time
import re
import os

if os.path.exists('/content/tunnel.log'):
    os.remove('/content/tunnel.log')

print("... Generando enlace Cloudflare")
time.sleep(7)

try:
    with open('/content/tunnel.log', 'r') as f:
        texto = f.read()
        enlace = re.search(r'https://[a-zA-Z0-9-]+\.trycloudflare\.com', texto)
        if enlace:
            print("\n" + "🟢"*20)
            print("Enlace:")
            print("\n👉  " + enlace.group(0) + "  👈\n")
            print("🟢"*20)
        else:
            print("⚠️ Si tarda, refrescar :)")
except Exception as e:
    print("Error:", e)
